/**
 ** Supermodel
 ** A Sega Model 3 Arcade Emulator.
 ** Copyright 2003-2025 The Supermodel Team
 **
 ** This file is part of Supermodel.
 **
 ** Supermodel is free software: you can redistribute it and/or modify it under
 ** the terms of the GNU General Public License as published by the Free
 ** Software Foundation, either version 3 of the License, or (at your option)
 ** any later version.
 **
 ** Supermodel is distributed in the hope that it will be useful, but WITHOUT
 ** ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 ** FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 ** more details.
 **
 ** You should have received a copy of the GNU General Public License along
 ** with Supermodel.  If not, see <http://www.gnu.org/licenses/>.
 **/

/*
 * DojoConfigFile.h
 *
 * Dojo Supermodel.ini.
 */

 #ifndef INCLUDED_DOJOCONFIGFILE_H
 #define INCLUDED_DOJOCONFIGFILE_H

 static const char s_dojoConfigFileContents[] =
 {
"[Global]\n"
"AddressOut = 127.0.0.1\n"
"Crosshairs = 0\n"
"DirectInputConstForceMax = 0\n"
"DirectInputFrictionMax = 0\n"
"DirectInputSelfCenterMax = 0\n"
"DirectInputVibrateMax = 0\n"
"EmulateDSB = 1\n"
"EmulateSound = 1\n"
"FlipStereo = 0\n"
"ForceFeedback = 0\n"
"FullScreen = 0\n"
"GPUMultiThreaded = 1\n"
"InputAccelerator = KEY_UP,JOY1_UP\n"
"InputAnalogGunDown = KEY_DOWN\n"
"InputAnalogGunDown2 = NONE\n"
"InputAnalogGunLeft = KEY_LEFT\n"
"InputAnalogGunLeft2 = NONE\n"
"InputAnalogGunRight = KEY_RIGHT\n"
"InputAnalogGunRight2 = NONE\n"
"InputAnalogGunUp = KEY_UP\n"
"InputAnalogGunUp2 = NONE\n"
"InputAnalogGunX = MOUSE_XAXIS,JOY1_XAXIS\n"
"InputAnalogGunX2 = NONE\n"
"InputAnalogGunY = MOUSE_YAXIS,JOY1_YAXIS\n"
"InputAnalogGunY2 = NONE\n"
"InputAnalogJoyDown = KEY_DOWN\n"
"InputAnalogJoyEvent = KEY_S,JOY_BUTTON2,MOUSE_RIGHT_BUTTON\n"
"InputAnalogJoyEvent2 = NONE\n"
"InputAnalogJoyLeft = KEY_LEFT\n"
"InputAnalogJoyRight = KEY_RIGHT\n"
"InputAnalogJoyTrigger = KEY_A,JOY_BUTTON1,MOUSE_LEFT_BUTTON\n"
"InputAnalogJoyTrigger2 = KEY_D,JOY_BUTTON2\n"
"InputAnalogJoyUp = KEY_UP\n"
"InputAnalogJoyX = JOY_XAXIS,MOUSE_XAXIS\n"
"InputAnalogJoyY = JOY_YAXIS,MOUSE_YAXIS\n"
"InputAnalogTriggerLeft = KEY_A,JOY1_BUTTON1,MOUSE_LEFT_BUTTON\n"
"InputAnalogTriggerLeft2 = NONE\n"
"InputAnalogTriggerRight = KEY_S,JOY1_BUTTON2,MOUSE_RIGHT_BUTTON\n"
"InputAnalogTriggerRight2 = NONE\n"
"InputAutoTrigger = 0\n"
"InputAutoTrigger2 = 0\n"
"InputBeat = KEY_S,JOY1_BUTTON2\n"
"InputBrake = KEY_DOWN,JOY1_DOWN\n"
"InputCharge = KEY_D,JOY1_BUTTON3\n"
"InputCoin1 = KEY_1\n"
"InputCoin2 = KEY_2\n"
"InputEscape = KEY_G\n"
"InputEscape2 = KEY_U\n"
"InputFishingCast = KEY_Z,JOY1_BUTTON1\n"
"InputFishingReel = KEY_SPACE,JOY1_ZAXIS_POS\n"
"InputFishingRodDown = KEY_DOWN\n"
"InputFishingRodLeft = KEY_LEFT\n"
"InputFishingRodRight = KEY_RIGHT\n"
"InputFishingRodUp = KEY_UP\n"
"InputFishingRodX = JOY1_XAXIS\n"
"InputFishingRodY = JOY1_YAXIS\n"
"InputFishingSelect = KEY_X,JOY1_BUTTON2\n"
"InputFishingStickDown = KEY_S\n"
"InputFishingStickLeft = KEY_A\n"
"InputFishingStickRight = KEY_D\n"
"InputFishingStickUp = KEY_W\n"
"InputFishingStickX = JOY1_RXAXIS\n"
"InputFishingStickY = JOY1_RYAXIS\n"
"InputFishingTension = KEY_T,JOY1_ZAXIS_NEG\n"
"InputGearShift1 = KEY_Q,JOY1_BUTTON5\n"
"InputGearShift2 = KEY_W,JOY1_BUTTON6\n"
"InputGearShift3 = KEY_E,JOY1_BUTTON7\n"
"InputGearShift4 = KEY_R,JOY1_BUTTON8\n"
"InputGearShiftDown = KEY_H\n"
"InputGearShiftN = KEY_T\n"
"InputGearShiftUp = KEY_Y\n"
"InputGuard = KEY_B\n"
"InputGuard2 = KEY_J\n"
"InputGunDown = KEY_DOWN\n"
"InputGunDown2 = NONE\n"
"InputGunLeft = KEY_LEFT\n"
"InputGunLeft2 = NONE\n"
"InputGunRight = KEY_RIGHT\n"
"InputGunRight2 = NONE\n"
"InputGunUp = KEY_UP\n"
"InputGunUp2 = NONE\n"
"InputGunX = MOUSE_XAXIS,JOY1_XAXIS\n"
"InputGunX2 = JOY2_XAXIS\n"
"InputGunY = MOUSE_YAXIS,JOY1_YAXIS\n"
"InputGunY2 = JOY2_YAXIS\n"
"InputHandBrake = KEY_S,JOY1_BUTTON2\n"
"InputJoyDown = KEY_DOWN\n"
"InputJoyDown2 = KEY_S\n"
"InputJoyLeft = KEY_LEFT\n"
"InputJoyLeft2 = KEY_A\n"
"InputJoyRight = KEY_RIGHT\n"
"InputJoyRight2 = KEY_D\n"
"InputJoyUp = KEY_UP\n"
"InputJoyUp2 = KEY_W\n"
"InputJump = KEY_F,JOY1_BUTTON4\n"
"InputKick = KEY_M\n"
"InputKick2 = KEY_L\n"
"InputLongPass = KEY_S,JOY1_BUTTON2\n"
"InputLongPass2 = JOY2_BUTTON2\n"
"InputMagicalLever1 = JOY1_YAXIS\n"
"InputMagicalLever2 = JOY2_YAXIS\n"
"InputMagicalLeverDown1 = KEY_DOWN\n"
"InputMagicalLeverDown2 = NONE\n"
"InputMagicalLeverUp1 = KEY_UP\n"
"InputMagicalLeverUp2 = NONE\n"
"InputMagicalPedal1 = KEY_A,JOY1_BUTTON1\n"
"InputMagicalPedal2 = KEY_S,JOY2_BUTTON1\n"
"InputMusicSelect = KEY_D,JOY1_BUTTON3\n"
"InputOffscreen = KEY_S,JOY1_BUTTON2,MOUSE_RIGHT_BUTTON\n"
"InputOffscreen2 = JOY2_BUTTON2\n"
"InputPunch = KEY_N\n"
"InputPunch2 = KEY_K\n"
"InputRearBrake = KEY_S,JOY1_BUTTON2\n"
"InputServiceA = KEY_5\n"
"InputServiceB = KEY_7\n"
"InputShift = KEY_A,JOY1_BUTTON1\n"
"InputShoot = KEY_D,JOY1_BUTTON3\n"
"InputShoot2 = JOY2_BUTTON3\n"
"InputShortPass = KEY_A,JOY1_BUTTON1\n"
"InputShortPass2 = JOY2_BUTTON1\n"
"InputSkiDown = KEY_DOWN\n"
"InputSkiLeft = KEY_LEFT\n"
"InputSkiPollLeft = KEY_A,JOY1_BUTTON1\n"
"InputSkiPollRight = KEY_S,JOY1_BUTTON2\n"
"InputSkiRight = KEY_RIGHT\n"
"InputSkiSelect1 = KEY_Q,JOY1_BUTTON3\n"
"InputSkiSelect2 = KEY_W,JOY1_BUTTON4\n"
"InputSkiSelect3 = KEY_E,JOY1_BUTTON5\n"
"InputSkiUp = KEY_UP\n"
"InputSkiX = JOY1_XAXIS\n"
"InputSkiY = JOY1_YAXIS\n"
"InputStart1 = KEY_RETURN\n"
"InputStart2 = KEY_SEMICOLON\n"
"InputSteering = JOY1_XAXIS\n"
"InputSteeringLeft = KEY_LEFT\n"
"InputSteeringRight = KEY_RIGHT\n"
"InputTestA = KEY_6\n"
"InputTestB = KEY_8\n"
"InputTrigger = KEY_A,JOY1_BUTTON1,MOUSE_LEFT_BUTTON\n"
"InputTrigger2 = JOY2_BUTTON1\n"
"InputTwinJoyCrouch = KEY_R,JOY1_BUTTON2\n"
"InputTwinJoyDown1 = NONE\n"
"InputTwinJoyDown2 = NONE\n"
"InputTwinJoyForward = KEY_UP,JOY1_YAXIS_NEG\n"
"InputTwinJoyJump = KEY_E,JOY1_BUTTON1\n"
"InputTwinJoyLeft1 = NONE\n"
"InputTwinJoyLeft2 = NONE\n"
"InputTwinJoyReverse = KEY_DOWN,JOY1_YAXIS_POS\n"
"InputTwinJoyRight1 = NONE\n"
"InputTwinJoyRight2 = NONE\n"
"InputTwinJoyShot1 = KEY_A,JOY1_BUTTON5\n"
"InputTwinJoyShot2 = KEY_S,JOY1_BUTTON6\n"
"InputTwinJoyStrafeLeft = KEY_LEFT,JOY1_XAXIS_NEG\n"
"InputTwinJoyStrafeRight = KEY_RIGHT,JOY1_XAXIS_POS\n"
"InputTwinJoyTurbo1 = KEY_Z,JOY1_BUTTON7\n"
"InputTwinJoyTurbo2 = KEY_X,JOY1_BUTTON8\n"
"InputTwinJoyTurnLeft = KEY_Q,JOY1_RXAXIS_NEG\n"
"InputTwinJoyTurnRight = KEY_W,JOY1_RXAXIS_POS\n"
"InputTwinJoyUp1 = NONE\n"
"InputTwinJoyUp2 = NONE\n"
"InputViewChange = KEY_A,JOY1_BUTTON1\n"
"InputVR1 = KEY_A,JOY1_BUTTON1\n"
"InputVR2 = KEY_S,JOY1_BUTTON2\n"
"InputVR3 = KEY_D,JOY1_BUTTON3\n"
"InputVR4 = KEY_F,JOY1_BUTTON4\n"
"LegacySoundDSP = 0\n"
"MultiTexture = 1\n"
"MultiThreaded = 1\n"
"MusicVolume = 75\n"
"NativeRefresh = 0\n"
"Network = 0\n"
"New3DEngine = 1\n"
"PortIn = 1970\n"
"PortOut = 1971\n"
"PowerPCFrequency = 50\n"
"QuadRendering = 1\n"
"RecordSession = 1\n"
"RefreshRate = 60\n"
"ShowFrameRate = 1\n"
"SimulateNet = true\n"
"SoundVolume = 75\n"
"Stretch = 0\n"
"Throttle = 1\n"
"VSync = 0\n"
"WideBackground = 0\n"
"WideScreen = 0\n"
"XInputConstForceMax = 0\n"
"XInputConstForceThreshold = 0\n"
"XInputVibrateMax = 0\n"
"XResolution = 800\n"
"YResolution = 600\n"

 };

 #endif  // INCLUDED_DOJOCONFIGFILE_H